name: Deploy blog

on:
  workflow_run:
    workflows: [Spellcheck]
    branches: [master]
    types:
      - completed
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy blog to site
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Create ssh key from repository secret
        run: |
          install -m 600 -D /dev/stdin ~/.ssh/id_ed25519 <<< "${{ secrets.WWW_PRIVATE_KEY }}"

      - name: Add blog site fingerprint to known ssh hosts
        run: ssh-keyscan -H aftix.xyz > ~/.ssh/known_hosts

      - name: Build site
        run: >
          nix build '.#packages.x86_64-linux.default'

      - name: Deploy site
        run: |
          scp result/site.tar.bz2 "www@aftix.xyz:/srv/site.tar.bz2"
          ssh "www@aftix.xyz" 'sh -ls' <<< "$SCRIPT"
        env:
          SCRIPT: >-
            cd /srv ;
            tar xvf site.tar.bz2 ;
            rm site.tar.bz2 ; 
            rm -rf aftix.xyz ;
            mv public aftix.xyz
