name: Spellcheck

on:
  pull_request:
  push:
    branches: [master]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Spellcheck
        run: >
          nix build .#checks.x86_64-linux.spelling
